CREATE SCHEMA IF NOT EXISTS commerce;

SET search_path TO commerce, public;

CREATE TABLE IF NOT EXISTS customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    full_name text NOT NULL,
    region text NOT NULL,
    country_code char(2) NOT NULL DEFAULT 'US',
    created_at timestamptz NOT NULL,
    CONSTRAINT customers_email_format_check CHECK (position('@' in email) > 1),
    CONSTRAINT customers_full_name_check CHECK (length(btrim(full_name)) > 0),
    CONSTRAINT customers_region_check CHECK (
        region IN ('Northeast', 'Midwest', 'South', 'West', 'International')
    ),
    CONSTRAINT customers_country_code_check CHECK (country_code ~ '^[A-Z]{2}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS customers_email_lower_uq
    ON customers (lower(email));

CREATE INDEX IF NOT EXISTS customers_region_idx
    ON customers (region);

CREATE TABLE IF NOT EXISTS categories (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id bigint REFERENCES categories (category_id) ON DELETE RESTRICT,
    name text NOT NULL,
    CONSTRAINT categories_name_check CHECK (length(btrim(name)) > 0),
    CONSTRAINT categories_not_self_parent_check CHECK (
        parent_category_id IS NULL OR parent_category_id <> category_id
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS categories_name_lower_uq
    ON categories (lower(name));

CREATE INDEX IF NOT EXISTS categories_parent_category_id_idx
    ON categories (parent_category_id);

CREATE TABLE IF NOT EXISTS products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories (category_id) ON DELETE RESTRICT,
    sku text NOT NULL UNIQUE,
    name text NOT NULL,
    unit_price_cents integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    launched_at date NOT NULL,
    discontinued_at date,
    CONSTRAINT products_sku_check CHECK (sku ~ '^[A-Z0-9-]+$'),
    CONSTRAINT products_name_check CHECK (length(btrim(name)) > 0),
    CONSTRAINT products_unit_price_check CHECK (unit_price_cents >= 0),
    CONSTRAINT products_date_order_check CHECK (
        discontinued_at IS NULL OR discontinued_at >= launched_at
    )
);

CREATE INDEX IF NOT EXISTS products_category_id_idx
    ON products (category_id);

CREATE INDEX IF NOT EXISTS products_active_idx
    ON products (active);

CREATE TABLE IF NOT EXISTS orders (
    order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES customers (customer_id) ON DELETE RESTRICT,
    order_number text NOT NULL UNIQUE,
    ordered_at timestamptz NOT NULL,
    status text NOT NULL,
    billing_region text NOT NULL,
    currency char(3) NOT NULL DEFAULT 'USD',
    subtotal_cents integer NOT NULL,
    discount_cents integer NOT NULL DEFAULT 0,
    tax_cents integer NOT NULL DEFAULT 0,
    shipping_cents integer NOT NULL DEFAULT 0,
    total_cents integer NOT NULL,
    CONSTRAINT orders_order_number_check CHECK (order_number ~ '^ORD-[0-9]{4}$'),
    CONSTRAINT orders_status_check CHECK (
        status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')
    ),
    CONSTRAINT orders_billing_region_check CHECK (
        billing_region IN ('Northeast', 'Midwest', 'South', 'West', 'International')
    ),
    CONSTRAINT orders_currency_check CHECK (currency = 'USD'),
    CONSTRAINT orders_amounts_nonnegative_check CHECK (
        subtotal_cents >= 0
        AND discount_cents >= 0
        AND tax_cents >= 0
        AND shipping_cents >= 0
        AND total_cents >= 0
    ),
    CONSTRAINT orders_total_matches_components_check CHECK (
        total_cents = subtotal_cents - discount_cents + tax_cents + shipping_cents
    ),
    CONSTRAINT orders_discount_lte_subtotal_check CHECK (discount_cents <= subtotal_cents)
);

CREATE INDEX IF NOT EXISTS orders_customer_id_idx
    ON orders (customer_id);

CREATE INDEX IF NOT EXISTS orders_ordered_at_idx
    ON orders (ordered_at);

CREATE INDEX IF NOT EXISTS orders_status_idx
    ON orders (status);

CREATE INDEX IF NOT EXISTS orders_customer_ordered_at_idx
    ON orders (customer_id, ordered_at);

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders (order_id) ON DELETE RESTRICT,
    product_id bigint NOT NULL REFERENCES products (product_id) ON DELETE RESTRICT,
    quantity integer NOT NULL,
    unit_price_cents integer NOT NULL,
    discount_cents integer NOT NULL DEFAULT 0,
    line_total_cents integer NOT NULL,
    CONSTRAINT order_items_quantity_check CHECK (quantity > 0),
    CONSTRAINT order_items_amounts_nonnegative_check CHECK (
        unit_price_cents >= 0 AND discount_cents >= 0 AND line_total_cents >= 0
    ),
    CONSTRAINT order_items_total_matches_components_check CHECK (
        line_total_cents = (quantity * unit_price_cents) - discount_cents
    ),
    CONSTRAINT order_items_discount_lte_line_check CHECK (
        discount_cents <= quantity * unit_price_cents
    ),
    CONSTRAINT order_items_order_product_uq UNIQUE (order_id, product_id)
);

CREATE INDEX IF NOT EXISTS order_items_order_id_idx
    ON order_items (order_id);

CREATE INDEX IF NOT EXISTS order_items_product_id_idx
    ON order_items (product_id);

CREATE TABLE IF NOT EXISTS payments (
    payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders (order_id) ON DELETE RESTRICT,
    provider_payment_id text NOT NULL UNIQUE,
    payment_method text NOT NULL,
    status text NOT NULL,
    amount_cents integer NOT NULL,
    paid_at timestamptz,
    CONSTRAINT payments_provider_payment_id_check CHECK (length(btrim(provider_payment_id)) > 0),
    CONSTRAINT payments_method_check CHECK (
        payment_method IN ('card', 'paypal', 'gift_card', 'bank_transfer')
    ),
    CONSTRAINT payments_status_check CHECK (
        status IN ('authorized', 'captured', 'failed', 'partially_refunded', 'refunded')
    ),
    CONSTRAINT payments_amount_check CHECK (amount_cents > 0),
    CONSTRAINT payments_captured_at_check CHECK (
        status NOT IN ('captured', 'partially_refunded', 'refunded') OR paid_at IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS payments_order_id_idx
    ON payments (order_id);

CREATE INDEX IF NOT EXISTS payments_status_idx
    ON payments (status);

CREATE INDEX IF NOT EXISTS payments_paid_at_idx
    ON payments (paid_at);

CREATE TABLE IF NOT EXISTS refunds (
    refund_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id bigint NOT NULL REFERENCES payments (payment_id) ON DELETE RESTRICT,
    external_refund_id text NOT NULL UNIQUE,
    status text NOT NULL,
    reason text NOT NULL,
    amount_cents integer NOT NULL,
    refunded_at timestamptz,
    CONSTRAINT refunds_external_refund_id_check CHECK (length(btrim(external_refund_id)) > 0),
    CONSTRAINT refunds_status_check CHECK (status IN ('pending', 'succeeded', 'failed')),
    CONSTRAINT refunds_reason_check CHECK (
        reason IN ('customer_return', 'damaged_item', 'shipping_delay', 'duplicate_charge')
    ),
    CONSTRAINT refunds_amount_check CHECK (amount_cents > 0),
    CONSTRAINT refunds_succeeded_at_check CHECK (
        status <> 'succeeded' OR refunded_at IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS refunds_payment_id_idx
    ON refunds (payment_id);

CREATE INDEX IF NOT EXISTS refunds_status_idx
    ON refunds (status);

CREATE INDEX IF NOT EXISTS refunds_refunded_at_idx
    ON refunds (refunded_at);

CREATE TABLE IF NOT EXISTS shipments (
    shipment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders (order_id) ON DELETE RESTRICT,
    shipment_number text NOT NULL UNIQUE,
    carrier text NOT NULL,
    tracking_number text UNIQUE,
    status text NOT NULL,
    shipped_at timestamptz,
    delivered_at timestamptz,
    CONSTRAINT shipments_shipment_number_check CHECK (shipment_number ~ '^SHP-[0-9]{4}$'),
    CONSTRAINT shipments_carrier_check CHECK (
        carrier IN ('UPS', 'FedEx', 'USPS', 'DHL', 'LocalCourier')
    ),
    CONSTRAINT shipments_status_check CHECK (
        status IN ('pending', 'shipped', 'delivered', 'returned', 'lost', 'cancelled')
    ),
    CONSTRAINT shipments_tracking_number_check CHECK (
        tracking_number IS NULL OR length(btrim(tracking_number)) > 0
    ),
    CONSTRAINT shipments_delivery_after_ship_check CHECK (
        shipped_at IS NULL OR delivered_at IS NULL OR delivered_at >= shipped_at
    ),
    CONSTRAINT shipments_delivered_at_check CHECK (
        status <> 'delivered' OR delivered_at IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS shipments_order_id_idx
    ON shipments (order_id);

CREATE INDEX IF NOT EXISTS shipments_status_idx
    ON shipments (status);

CREATE INDEX IF NOT EXISTS shipments_shipped_at_idx
    ON shipments (shipped_at);

CREATE INDEX IF NOT EXISTS shipments_delivered_at_idx
    ON shipments (delivered_at);
