CREATE SCHEMA IF NOT EXISTS text_to_sql_audit;

CREATE TABLE IF NOT EXISTS text_to_sql_audit.query_audit_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id text NOT NULL UNIQUE,
    normalized_question text NOT NULL,
    generated_sql text,
    outcome text NOT NULL CHECK (
        outcome IN ('success', 'clarification_required', 'blocked', 'failed')
    ),
    blocked_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
    execution_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    confidence_breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
    provider_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS query_audit_records_created_at_idx
    ON text_to_sql_audit.query_audit_records (created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS text_to_sql_audit.query_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id text NOT NULL REFERENCES text_to_sql_audit.query_audit_records (request_id)
        ON DELETE CASCADE,
    rating text NOT NULL CHECK (rating IN ('correct', 'incorrect', 'unsure')),
    comment text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS query_feedback_request_id_idx
    ON text_to_sql_audit.query_feedback (request_id);
